### ISSUE TITLE
hou to build？

### ISSUE THREAD

**Issue by dwm97317** [fastogt/pyfastotv#1]
Your previous project has been deleted. There is currently no documentation here. I don't know how to proceed.

**Comment by topilski** [comment]
This is only submodule, our projects in private repos.

**Comment by dwm97317** [comment]
Hello, I saw your post on reddit.com, free test, I want to apply to test your project.

**Comment by topilski** [comment]
You can do all test on test server: https://fastocloud.com

**Comment by dwm97317** [comment]
English
我已经进去过了，目前就是想在我个人服务器上部署你们的项目，如果可以，我想成为你们的客户

我已经进去过了，目前就是想在我个人服务器上部署你们的项目，如果可以，我想成为你们的客户
Wǒ yǐjīng jìnqùguòle, mùqián jiùshì xiǎng zài wǒ gèrén fúwùqì shàng bùshǔ nǐmen de xiàngmù, rúguǒ kěyǐ, wǒ xiǎng chéngwéi nǐmen de kèhù
I have already gone in. I want to deploy your project on my personal server. If I can, I want to be your customer.
